version: '2.23'

services:
  postgres-compose: 
    image: postgres
    container_name: postgres
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always 

volumes:
  postgres-data: